version: 2.1
description: |
  This orb is for NeuVector vulnerability scanning.
display:
  home_url: https://neuvector.com/
  source_url: https://github.com/neuvector/circleci-orb/
examples:
  image-scan:
    description: Scan a image
    usage:
      version: 2.1
      orbs:
        neuvector: neuvector/neuvector-orb@1.1.0
      jobs:
        build_image:
          docker:
            - image: docker:stable-git
          steps:
            - setup_remote_docker
            - checkout
            - run:
                name: build container
                command: |
                  docker pull alpine:3.2
            - run:
                name: Save Docker image
                command: |
                  rm -rf /tmp/neuvector/
                  mkdir /tmp/neuvector/ -p
                  docker save -o /tmp/neuvector/alpine-3.2.tar alpine:3.2
            - persist_to_workspace:
                root: /tmp/neuvector/
                paths:
                  - ./
      workflows:
        scan-image:
          jobs:
            - neuvector/scan-image:
                context: myContext
                registry_url: https://registry.hub.docker.com
                repository: library/alpine
                tag: "3.12.0"
                scan_layers: false
                high_vul_to_fail: 0
                medium_vul_to_fail: 3
        scan-private-registry:
          jobs:
            - neuvector/scan-image:
                context: myContext
                registry_url: 127.100.12.157:5000
                registry_username: ${registry_username}
                registry_password: ${registry_password}
                repository: ci_demo_image
                tag: "v1.2"
                scan_layers: false
                high_vul_to_fail: 10
                medium_vul_to_fail: 30
        scan-local-image:
          jobs:
            - build_image
            - neuvector/scan-image:
                requires:
                  - build_image
                context: myContext
                scan_local_image: true
                image_name: alpine
                image_tag: "3.2"
                path: "/tmp/neuvector/"
                image_tar_file: /tmp/neuvector/alpine-3.2.tar
                scan_layers: false
                high_vul_to_fail: 0
                medium_vul_to_fail: 3
executors:
  default:
    machine: true
commands:
  load_image:
    description: Load image
    parameters:
      image_tar_file:
        description: The tar archive file that stores the to-be-scan image
        type: string
      path:
        description: The absolute path to store the tar archive file
        type: string
    steps:
      - run:
          name: Load the to-be-scan image from the attached tar archive file
          command: |
            docker load -i <<parameters.path>><<parameters.image_tar_file>>
  scan_on_dynamic:
    description: run NeuVector Scanner
    parameters:
      registry:
        description: The registry to pull NeuVector Scanner
        type: string
      username:
        description: The registry's login user
        type: string
      password:
        description: The registry's login password
        type: string
      scanner_image:
        description: Neuvector Scanner image
        type: string
      repository:
        description: The repository to scan
        type: string
      tag:
        description: Tag of the repository to scan
        type: string
    steps:
      - run:
          name: Start up Neuvector Scanner
          command: |
            echo "<<parameters.password>>" | docker login --username "<<parameters.username>>" <<parameters.registry>> --password-stdin
            docker run --name neuvector.scanner --rm -e SCANNER_REPOSITORY=<<parameters.repository>> -e SCANNER_TAG=<<parameters.tag>> -e SCANNER_ON_DEMAND=true -v /var/run/docker.sock:/var/run/docker.sock -v /var/neuvector:/var/neuvector '<<parameters.scanner_image>>'
            mkdir nvreport
            cp /var/neuvector/scan_result.json ./nvreport/scan_repository.json
  scan:
    description: Scan image
    parameters:
      controller_ip:
        description: The IP address of NeuVector Scanner
        type: string
        default: $controller_ip
      controller_port:
        description: The port to access NeuVector Scanner
        type: string
        default: $controller_port
      controller_username:
        description: Username to sign in NeuVector Scanner
        type: string
        default: $controller_username
      controller_password:
        description: Password to sign in NeuVector Scanner
        type: string
        default: $controller_password
      registry_url:
        description: The registry URL full path
        type: string
        default: ''
      registry_username:
        description: The registry Username
        type: string
        default: ''
      registry_password:
        description: The registry password
        type: string
        default: ''
      repository:
        description: The repository to scan
        type: string
      tag:
        description: Tag of the repository to scan
        type: string
      scan_layers:
        description: Scan layer
        type: boolean
        default: false
      md_source:
        description: Source name
        type: string
        default: ''
    steps:
      - run:
          name: Scan Image
          command: |
            mkdir nvtemp
            mkdir nvreport
            curl --silent --write-out "HTTPSTATUS:%{http_code}" -k -H "Content-Type: application/json" -d '{"password": {"username": "'<<parameters.controller_username>>'", "password": "'<<parameters.controller_password>>'"}}' "https://<<parameters.controller_ip>>:<<parameters.controller_port>>/v1/auth" > ./nvtemp/tokenResponse
            HTTP_STATUS=$(cat ./nvtemp/tokenResponse | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
            if [ "$HTTP_STATUS" == "200" ]; then
              cat ./nvtemp/tokenResponse | sed -e 's/HTTPSTATUS\:.*//g' > ./nvtemp/token.json
            elif [ "$HTTP_STATUS" == "401" -o "$HTTP_STATUS" == "404" -o "$HTTP_STATUS" == "405" ]; then
              echo Invalid credential of NeuVector controller.
              exit 1
            else
              echo Failed to get token. Http status code: $HTTP_STATUS.
              exit 1
            fi

            curl --silent --write-out "HTTPSTATUS:%{http_code}" -k -H "Content-Type: application/json" -H "X-Auth-Token: `cat ./nvtemp/token.json | jq -r '.token.token'`" "https://<<parameters.controller_ip>>:<<parameters.controller_port>>/v1/scan/scanner" > ./nvtemp/scannerResponse
            _status_=$(cat ./nvtemp/scannerResponse | sed -e 's/HTTPSTATUS\:.*//g' | jq .scanners[])
            _counter_="0"
            while [ -z "$_status_" -a "$_counter_" != "20" ]; do
              _counter_=$((( _counter_ + 1 )))
              sleep 5
              curl --silent --write-out "HTTPSTATUS:%{http_code}" -k -H "Content-Type: application/json" -H "X-Auth-Token: `cat ./nvtemp/token.json | jq -r '.token.token'`" "https://<<parameters.controller_ip>>:<<parameters.controller_port>>/v1/scan/scanner" > ./nvtemp/scannerResponse
              _status_=$(cat ./nvtemp/scannerResponse | sed -e 's/HTTPSTATUS\:.*//g' | jq .scanners[])
            done

            if [ "$_counter_" = "20" ]; then
              echo Neuvector Scanner is not available.
              exit 1
            fi

            curl --silent --write-out "HTTPSTATUS:%{http_code}" -k -H "Content-Type: application/json" -H "X-Auth-Token: `cat ./nvtemp/token.json | jq -r '.token.token'`" -d '{"request": { "metadata":{"source": "'<<parameters.md_source>>'", "user": "${CIRCLE_PROJECT_USERNAME}", "job": "${CIRCLE_PROJECT_REPONAME} ", "workspace": "${CIRCLE_WORKING_DIRECTORY}"}, "registry": "'<<parameters.registry_url>>'", "username": "'<<parameters.registry_username>>'", "password": "'<<parameters.registry_password>>'", "repository": "'<<parameters.repository>>'", "tag": "'<<parameters.tag>>'", "scan_layers": <<parameters.scan_layers>>}}' "https://<<parameters.controller_ip>>:<<parameters.controller_port>>/v1/scan/repository" > ./nvtemp/scanResponse
            HTTP_STATUS=$(cat ./nvtemp/scanResponse | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
            while [ "$HTTP_STATUS" == "304" ]; do
              curl --silent --write-out "HTTPSTATUS:%{http_code}" -k -H "Content-Type: application/json" -H "X-Auth-Token: `cat ./nvtemp/token.json | jq -r '.token.token'`" -d '{"request": { "metadata":{"source": "'<<parameters.md_source>>'", "user": "${CIRCLE_PROJECT_USERNAME}", "job": "${CIRCLE_PROJECT_REPONAME} ", "workspace": "${CIRCLE_WORKING_DIRECTORY}"}, "registry": "'<<parameters.registry_url>>'", "username": "'<<parameters.registry_username>>'", "password": "'<<parameters.registry_password>>'", "repository": "'<<parameters.repository>>'", "tag": "'<<parameters.tag>>'", "scan_layers": <<parameters.scan_layers>>}}' "https://<<parameters.controller_ip>>:<<parameters.controller_port>>/v1/scan/repository" > ./nvtemp/scanResponse
              HTTP_STATUS=$(cat ./nvtemp/scanResponse | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
            done
            if [ "$HTTP_STATUS" == "200" ]; then
              cat ./nvtemp/scanResponse | sed -e 's/HTTPSTATUS\:.*//g' > ./nvreport/scan_repository.json
              echo Scan successfully.
            else
              echo Scan failed. Http status code: $HTTP_STATUS.
              exit 1
            fi
            curl -k -X "DELETE" -H "Content-Type: application/json" -H "X-Auth-Token: `cat ./nvtemp/token.json | jq -r '.token.token'`" "https://<<parameters.controller_ip>>:<<parameters.controller_port>>/v1/auth"
  report:
    description: Print the report
    steps:
      - run:
          name: Short report
          command: |
            VUL_NUM=$(cat ./nvreport/scan_repository.json | jq '.report.vulnerabilities | length')
            if [ "$VUL_NUM" -eq 0 ]; then
              echo No vulnerabilities found.
            else
              echo Total number of vulnerabilities: $VUL_NUM, grouped by package name with vulnerability name.
              jq '[.report.vulnerabilities | group_by(.package_name) | .[] | {package_name: .[0].package_name, vuln_name: [.[].name]}]' ./nvreport/scan_repository.json
            fi
      - run:
          name: Full report
          command: |
            echo Full report in json.
            cat ./nvreport/scan_repository.json | jq .
  checkpoint:
    description: Check the scan result based on the criteria
    parameters:
      high_vul_to_fail:
        description: Minimum number of high vulnerabilities to fail the build
        type: integer
        default: 0
      medium_vul_to_fail:
        description: Minimum number of medium vulnerabilities to fail the build
        type: integer
        default: 0
    steps:
      - run:
          name: Check criteria
          command: |
            FOUND_HIGH=$(cat ./nvreport/scan_repository.json | jq '.report.vulnerabilities[] | select(.severity == "High") | .severity' | wc -l)
            FOUND_MEDIUM=$(cat ./nvreport/scan_repository.json | jq '.report.vulnerabilities[] | select(.severity == "Medium") | .severity' | wc -l)
            echo Criteria high_vul_to_fail: <<parameters.high_vul_to_fail>>, medium_vul_to_fail: <<parameters.medium_vul_to_fail>>.
            echo Found high vulnerabilities: $FOUND_HIGH, found medium vulnerabilities: $FOUND_MEDIUM.
            if [ <<parameters.high_vul_to_fail>> -ne 0 -a "$FOUND_HIGH" -ge <<parameters.high_vul_to_fail>> ]; then
              echo Fail due to high vulnerabilities found meets the criteria.
              exit 1
            elif [ <<parameters.medium_vul_to_fail>> -ne 0 -a "$FOUND_MEDIUM" -ge <<parameters.medium_vul_to_fail>> ]; then
              echo Fail due to medium vulnerabilities found meets the criteria.
              exit 1
            else
              echo Pass the criteria check.
            fi

jobs:
  scan-image:
    executor: default
    parameters:
      scan_local_image:
        description: To scan the image on the same host
        type: boolean
        default: false
      image_tar_file:
        description: Tar file exported from docker running container
        type: string
      path:
        description: The absolute path to store the tar file
        type: string
      image_name:
        description: Name of the image to be scanned
        type: string
      image_tag:
        description: Tag of the image to be scanned
        type: string
      nv_registry_url:
        description: Registry URL to pull NeuVector Scanner Image
        type: string
        default: ${nv_registry_url}
      nv_registry_username:
        description: Login user to pull NeuVector Scanner Image
        type: string
        default: ${nv_registry_username}
      nv_registry_password:
        description: Login password pull NeuVector Scanner Image
        type: string
        default: ${nv_registry_password}
      nv_scanner_image:
        description: The Neuvector Scanner image
        type: string
        default: "neuvector/scanner:latest"
      controller_ip:
        description: The IP address of the Controller or Allinone host or service external ip
        type: string
        default: $controller_ip
      controller_port:
        description: The port for REST API
        type: string
        default: $controller_port
      controller_username:
        description: Username for a NeuVector admin
        type: string
        default: $controller_username
      controller_password:
        description: Password for a NeuVector admin
        type: string
        default: $controller_password
      registry_url:
        description: The registry URL full path
        type: string
        default: ''
      registry_username:
        description: The registry Username
        type: string
        default: ''
      registry_password:
        description: The registry password
        type: string
        default: ''
      repository:
        description: The repository to scan
        type: string
        default: ''
      tag:
        description: Tag of the repository to scan
        type: string
        default: ''
      scan_layers:
        description: Scan layer
        type: boolean
        default: false
      high_vul_to_fail:
        description: Minimum number of high vulnerabilities to fail the build
        type: integer
        default: 0
      medium_vul_to_fail:
        description: Minimum number of medium vulnerabilities to fail the build
        type: integer
        default: 0
      md_source:
        description: Metadata source name
        type: string
        default: "CircleCI"
    steps:
      - when:
          condition: <<parameters.scan_local_image>>
          steps:
            - attach_workspace:
                at: <<parameters.path>>
            - load_image:
                image_tar_file: <<parameters.image_tar_file>>
                path: <<parameters.path>>
            - scan_on_dynamic:
                registry: <<parameters.nv_registry_url>>
                username: <<parameters.nv_registry_username>>
                password: <<parameters.nv_registry_password>>
                scanner_image: <<parameters.nv_scanner_image>>
                repository: <<parameters.image_name>>
                tag: <<parameters.image_tag>>
      - unless:
          condition: <<parameters.scan_local_image>>
          steps:
            - scan:
                registry_url: <<parameters.registry_url>>
                repository: <<parameters.repository>>
                registry_username: <<parameters.registry_username>>
                registry_password: <<parameters.registry_password>>
                tag: <<parameters.tag>>
                scan_layers: <<parameters.scan_layers>>
                md_source: <<parameters.md_source>>
      - report
      - checkpoint:
          high_vul_to_fail: <<parameters.high_vul_to_fail>>
          medium_vul_to_fail: <<parameters.medium_vul_to_fail>>
      - store_artifacts:
          path: nvreport
